# Generated by Django 4.1 on 2022-08-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_articleimage_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentAuthor', models.CharField(max_length=50, verbose_name='Username')),
                ('commentContent', models.CharField(max_length=200, verbose_name='Comment')),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article', verbose_name='Article')),
            ],
        ),
    ]
