# Generated by Django 4.1 on 2022-08-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-createdDate']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commentDate']},
        ),
    ]
